# install.packages('devtools') 
# install.packages('remotes')
# install.packages('spatstat.explore') 
# remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)
# install.packages('Seurat')
# if (!require("stringr", quietly = TRUE))
#   install.packages("stringr")
# if (!require("dplyr", quietly = TRUE))
#   install.packages("dplyr")
# sessionInfo('Seurat')
#install.packages('hdf5r')
# if (!require("Hmisc", quietly = TRUE))
#     install.packages("Hmisc")
# if (!require("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install(version = "3.17")
#BiocManager::install('monocle')
# if (!require("harmony", quietly = TRUE))
#   install.packages("harmony")
# if (!require("EnhancedVolcano", quietly = TRUE))
#   install.packages("EnhancedVolcano")
# install.packages(c("SeuratObject", "Seurat"))
# BiocManager::install('EnhancedVolcano')
# library(dplyr)
# BiocManager::install("DOSE")
# BiocManager::install("org.Hs.eg.db")
# BiocManager::install("clusterProfiler")
# BiocManager::install("enrichplot")
# BiocManager::install("GSVA")
# devtools::install_github("junjunlab/GseaVis")
# install.packages('paletteer')
# devtools::install_github("sqjin/CellChat")
# BiocManager::install("BiocNeighbors")
# BiocManager::install("ComplexHeatmap")

library(SeuratObject)
library(Seurat)

library(stringr)
library(dplyr)
library(hdf5r)
library(Hmisc)
library(cowplot)
library(ggplot2)

library(devtools)
library(remotes)

library(harmony)
library(sctransform) 
library(future)

library(monocle)

library(CellChat)
library(patchwork)


library(EnhancedVolcano)
library(DOSE)
library(org.Hs.eg.db)
library(clusterProfiler)
library(enrichplot)
library(GseaVis)
library(paletteer)
library(GSVA)
library(CellChat)
library(patchwork)
